* BashRepo

** About
   This is an attempt to create a library for reusable Bash code.

   BashRepo provides you an import function for your Bash code to
   import already defined Bash functions from network repositories.
   You can use the default repository, you can define your own
   repository or you can use other public repositories.  When you
   import a function from a repository it gets automatically
   downloaded and stored in your HOME direcotry.  This works a bit
   like Maven for JAR packages.  During your development the functions
   are sourced from your local repository.  If you have finished your
   work you have to release your program.  By this all imported
   functions are included into your program producing a single file
   without any dependencies.  The released program does not need any
   repositories any more.

** Usage
   Install the bashrepo program somewhere in your PATH.

   : install <(curl -sSL https://raw.githubusercontent.com/ceving/bashrepo/master/bashrepo) ~/bin/bashrepo


   Then you have to source it in your own script.

   : source bashrepo

   After that you can start importing functions from the repository.

   : import upper
   : import lower

   And then you can use them.

   : if [ $(echo abc | upper | lower) = abc ]; then
   :   echo fine
   : fi

   If you are ready with your development you have to use bashrepo to
   release your code before you can install it.

   : install <(bashrepo example/abc) ~/bin/abc

   The development version and the released version work in the same
   way.

   : if [ $(example/abc) = $(~/bin/abc) ]; then echo fine; fi
   : fine

   Use the -u option to update already downloaded functions.

   : bashrepo -u example/all

   Without the -u option BashRepo would not check any repository for
   newer versions of already downloaded functions.

** Requirements
   BashRepo needs an up to date Bash version supporting associative
   arrays and Curl to download code from repositories.  Curl is only
   needed during development.  After you have released your program
   Curl is not needed any more.

** License
   BashRepo is licensed under the [[license][GNU General Public License]].

#+LINK: license https://raw.githubusercontent.com/ceving/bashrepo/master/LICENSE
